#!/usr/bin/env python3
"""Generate portable C tables and sample-free BACnet point documentation.

Input is the checked-in sanitized factual catalog, not a network/device read.
Regeneration never contacts equipment and never imports captured sample values.
"""
import csv
import io
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]


def generate():
    doc = json.loads((ROOT / 'tools/ats_catalog.json').read_text())
    points, blocks = doc['points'], doc['blocks']
    assert len(points) == 164 and len(blocks) == 23
    assert [p['instance'] for p in points] == list(range(1001, 1165))
    assert len({p['name'] for p in points}) == len(points)
    assert len({(p['object_type'], p['instance']) for p in points}) == len(points)
    occupied = set()
    for block in blocks:
        addresses = set(range(block['offset'], block['offset']+block['count']))
        assert not (occupied & addresses)
        assert 1 <= block['count'] <= 40
        occupied |= addresses
    lines = ['/* Generated by tools/generate_ats_map.py; do not edit. */']
    for p in points:
        assert p['manual_access'] in ('RO', 'RW')  # Gateway never maps write-only registers.
        assert p['word_count'] <= 10
        assert all(p['offset'] + i in occupied for i in range(p['word_count']))
        if p['state_text']:
            lines.append('static const char *const states_%d[] = {%s};' % (
                p['instance'], ', '.join(json.dumps(s) for s in p['state_text'])))
    lines.append('\nconst ats_point_def_t ats_points[ATS_POINT_COUNT] = {')
    for p in points:
        states = 'states_%d' % p['instance'] if p['state_text'] else 'NULL'
        lines.append('    {%d, %du, %s, %s, %d, %d, %s, %d, %d, %d, %d},' % (
            p['object_type'], p['instance'], json.dumps(p['name']), json.dumps(p['description']),
            p['units'], len(p['state_text']), states, p['offset'], p['word_count'],
            p['bit_lsb'], p['bit_width']))
    lines += ['};', '\nstatic const point_decode_t point_decoders[ATS_POINT_COUNT] = {']
    lines += ['    {ENC_%s, %d, %d},' % (p['encoding'], p['scale_num'], p['scale_den']) for p in points]
    lines += ['};', '\nconst ats_scan_block_t ats_scan_blocks[ATS_BLOCK_COUNT] = {']
    lines += ['    {%d, %d, %du, %du, %s},' % (b['offset'], b['count'], b['period_ms'], b['stale_ms'], json.dumps(b['name'])) for b in blocks]
    lines += ['};', '']
    ctext = '\n'.join(lines)
    table = io.StringIO(newline='')
    fields = ['instance', 'bacnet_type', 'name', 'wire_offset', 'register_count', 'bits',
              'encoding', 'scale', 'bacnet_units', 'units', 'period_ms', 'stale_ms',
              'states', 'native_access', 'gateway_access', 'description']
    writer = csv.DictWriter(table, fieldnames=fields)
    writer.writeheader()
    for p in points:
        block = next(b for b in blocks if b['offset'] <= p['offset'] and p['offset']+p['word_count'] <= b['offset']+b['count'])
        writer.writerow(dict(instance=p['instance'], bacnet_type={0:'analogInput',3:'binaryInput',13:'multiStateInput',40:'characterStringValue'}[p['object_type']],
            name=p['name'], wire_offset=p['offset'], register_count=p['word_count'],
            bits='' if not p['bit_width'] else '%d:%d' % (p['bit_lsb'], p['bit_lsb']+p['bit_width']-1),
            encoding=p['encoding'], scale='%d/%d' % (p['scale_num'], p['scale_den']),
            bacnet_units=p['units'], units=p['units_label'], period_ms=block['period_ms'],
            stale_ms=block['stale_ms'], states='; '.join('%d=%s' % (i+1, s) for i,s in enumerate(p['state_text'])),
            native_access=p['manual_access'], gateway_access='read-only', description=p['description']))
    return {ROOT/'main/ats_map.inc': ctext, ROOT/'docs/points.csv': table.getvalue()}


def main():
    check = sys.argv[1:] == ['--check']
    if sys.argv[1:] and not check:
        raise SystemExit('Usage: generate_ats_map.py [--check]')
    for path, content in generate().items():
        if check:
            if path.open(newline='').read() != content:
                raise SystemExit(str(path) + ' requires regeneration')
        else:
            with path.open('w', newline='') as stream:
                stream.write(content)
    print('ATS point tables current' if check else 'Generated ATS C table and point map')


if __name__ == '__main__':
    main()
